load(":junit_test.bzl", "kt_test")

kt_test(
    name = "SimpleKotlinTest",
    size = "large",
    srcs = ["SimpleKotlinTest.kt"],
    classname = "SimpleKotlinTest",
)

java_library(
    name = "hello",
    srcs = ["nested_src/Hello.java"],
)
