load("@rules_java//java:java_test.bzl", "java_test")

java_test(
    name = "test_with_lib",
    srcs = [],
    deps = [],
    runtime_deps = ["//java/case3:test_library"],
    test_class = "case3.JavaTest",
)
